#!/bin/bash

for i in {1..2}
do
    DIR=$(date +%Y-%m-%d-%H-%M-%S)
    mkdir "runs/$DIR"

    cd "runs/$DIR"
    python ~/tcc/haremfmt.py ~/tcc/harem.xml -o spacy --split 0.7 --level paragraph

    mv harem.test harem-test.test
    mkdir json
    mkdir -p models/harem-holdout

    python -m spacy convert harem.train json/ -c iob
    python -m spacy convert harem-test.test json/ -c iob

    python -m spacy train pt models/harem-holdout/ json/harem.json json/harem.json

    python -m spacy evaluate models/harem-holdout/model-best/ json/harem-test.json

    cd ../../
done
