#!/bin/bash

rm json/harem-100.json
rm json/harem-100-test.json
python3 -m spacy convert harem-100.train json/ -c iob
python3 -m spacy convert harem-100-test.test json/ -c iob

rm -rf models/harem-100/*
python3 -m spacy train pt models/harem-100/ json/harem-100.json json/harem-100.json

python3 -m spacy evaluate models/harem-100/model-best/ json/harem-100.json
