#!/bin/bash

rm json/harem.json
rm json/harem-test.json
mv harem.test harem-test.test
python3 -m spacy convert harem.train json/ -c iob
python3 -m spacy convert harem-test.test json/ -c iob

rm -rf models/harem-holdout/*
python3 -m spacy train pt models/harem-holdout/ json/harem.json json/harem.json

python3 -m spacy evaluate models/harem-holdout/model-best/ json/harem-test.json
