#!/bin/bash

for x in 'pt-br-mix' 'pt-br-pt-br' 'pt-br-pt-pt'
do
    cd $x
    mkdir 1 2 3 4 5 6 7 8 9 10
    for i in {1..10}
    do
        cd $i
        mkdir k0 k1 k2 k3 k4 k5 k6 k7 k8 k9
        for j in k0 k1 k2 k3 k4 k5 k6 k7 k8 k9
        do
            cd $j
            case $x in
                'pt-br-pt-br')
                    python3 ../../../../../../haremfmt.py -o spacy -l paragraph -v pt-br -s 0.7 ../../../../../../harem.xml
                    mv pt-br.train train.train
                    mv pt-br.test test.test
                ;;
                'pt-br-mix')
                    python3 ../../../../../../haremfmt.py -o spacy -l paragraph -v pt-br -s 1.0 ../../../../../../harem.xml
                    mv pt-br.train train.train
                    python3 ../../../../../../haremfmt.py -o spacy -l paragraph -v mix -s 1.0 ../../../../../../harem.xml
                    mv mix.train test.test
                    ;;
                'pt-br-pt-pt')
                    python3 ../../../../../../haremfmt.py -o spacy -l paragraph -v pt-br -s 1.0 ../../../../../../harem.xml
                    mv pt-br.train train.train
                    python3 ../../../../../../haremfmt.py -o spacy -l paragraph -v pt-pt -s 1.0 ../../../../../../harem.xml
                    mv pt-pt.train test.test
                    ;;
            esac

            python3 -m spacy convert train.train . -c iob
            python3 -m spacy convert test.test . -c iob
            python3 -m spacy train pt models train.json train.json
            python3 -m spacy evaluate models/model-best/ test.json > saida.txt

            cd ..
        done
        cd ..
    done
    cd ..
done
