#!/bin/bash

for i in {1..10}
do
    cd $i
    for j in k0 k1 k2 k3 k4 k5 k6 k7 k8 k9
    do
        cd $j
        python3 -m spacy convert train.train . -c iob
        python3 -m spacy convert test.test . -c iob
        python3 -m spacy train pt models train.json train.json
        python3 -m spacy evaluate models/model-best/ test.json > saida.txt
        cd ..
    done
    cd ..
done
