#!/bin/bash

for i in {1..5}
do
    DIR=$(date +%Y-%m-%d-%H-%M-%S)
    mkdir "runs/$DIR"

    cd "runs/$DIR"
    python ~/tcc/haremfmt.py ~/tcc/harem.xml -o opennlp --split 0.7 --level paragraph

    opennlp TokenNameFinderTrainer -model harem.bin -data harem.train -encoding UTF-8 -lang pt

    opennlp TokenNameFinderEvaluator -model harem.bin -data harem.test >> result.txt

    cd ../../
done
