#!/bin/bash

# /home/d/Downloads/apache-opennlp-1.9.3/bin/
export PATH=$PATH:$HOME/Downloads/apache-opennlp-1.9.3/bin/
for x in 'pt-br-mix' 'pt-br-pt-br' 'ptbr-pt-pt'
do
    cd $x
    mkdir 1 2 3 4 5 6 7 8 9 10
    for i in {1..10}
    do
        cd $i
        mkdir k0 k1 k2 k3 k4 k5 k6 k7 k8 k9
        for j in k0 k1 k2 k3 k4 k5 k6 k7 k8 k9
        do
            cd $j
            case $x in
                'pt-br-pt-br')
                    python3 ../../../../../../haremfmt.py -o opennlp -l paragraph -v pt-br -s 0.7 ../../../../../../harem.xml
                    mv pt-br.train train.train
                    mv pt-br.test test.test
                ;;
                'pt-br-mix')
                    python3 ../../../../../../haremfmt.py -o opennlp -l paragraph -v pt-br -s 1.0 ../../../../../../harem.xml
                    mv pt-br.train train.train
                    python3 ../../../../../../haremfmt.py -o opennlp -l paragraph -v mix -s 1.0 ../../../../../../harem.xml
                    mv mix.train test.test
                    ;;
                'pt-br-pt-pt')
                    python3 ../../../../../../haremfmt.py -o opennlp -l paragraph -v pt-br -s 1.0 ../../../../../../harem.xml
                    mv pt-br.train train.train
                    python3 ../../../../../../haremfmt.py -o opennlp -l paragraph -v pt-pt -s 1.0 ../../../../../../harem.xml
                    mv mix.train test.test
                    ;;
            esac

            opennlp TokenNameFinderTrainer -model model.bin -lang pt -data train.train -encoding UTF-8
            opennlp TokenNameFinderEvaluator -model model.bin -data test.test -encoding UTF-8 > saida.txt
            cd ..
        done
        cd ..
    done
    cd ..
done
