#!/bin/bash

for x in 'pt-pt-mix' 'pt-pt-pt-br' 'pt-pt-pt-pt'
do
    cd $x
    mkdir 1 2 3 4 5 6 7 8 9 10
    for i in {1..10}
    do
        cd $i
        mkdir k0 k1 k2 k3 k4 k5 k6 k7 k8 k9
        for j in k0 k1 k2 k3 k4 k5 k6 k7 k8 k9
        do
            cd $j
            case $x in
                'pt-pt-pt-pt')
                    python3 ../../../../../../haremfmt.py -o corenlp -l paragraph -v pt-pt -s 0.7 ../../../../../../harem.xml
                    mv pt-pt.train train.train
                    mv pt-pt.test test.test
                ;;
                'pt-pt-mix')
                    python3 ../../../../../../haremfmt.py -o corenlp -l paragraph -v pt-pt -s 1.0 ../../../../../../harem.xml
                    mv pt-pt.train train.train
                    python3 ../../../../../../haremfmt.py -o corenlp -l paragraph -v mix -s 1.0 ../../../../../../harem.xml
                    mv mix.train test.test
                    ;;
                'pt-pt-pt-br')
                    python3 ../../../../../../haremfmt.py -o corenlp -l paragraph -v pt-pt -s 1.0 ../../../../../../harem.xml
                    mv pt-pt.train train.train
                    python3 ../../../../../../haremfmt.py -o corenlp -l paragraph -v pt-br -s 1.0 ../../../../../../harem.xml
                    mv pt-br.train test.test
                    ;;
            esac

            cp ../../../../props/harem-ptpt.prop harem.prop
            java -Xmx3G -cp ../../../../stanford-ner.jar edu.stanford.nlp.ie.crf.CRFClassifier -prop harem.prop
            java -Xmx3G -cp ../../../../stanford-ner.jar edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier model.ser.gz -testFile test.test > saida.txt 2>&1

            cd ..
        done
        cd ..
    done
    cd ..
done
