#!/bin/bash

for i in {1..5}
do
    DIR=$(date +%Y-%m-%d-%H-%M-%S)
    mkdir "runs/$DIR"

    cd "runs/$DIR"
    cp ../../props/harem-holdout.prop .
    python ~/tcc/haremfmt.py ~/tcc/harem.xml -o corenlp --split 0.7 --level paragraph

    java -mx3g -cp ../../stanford-ner.jar edu.stanford.nlp.ie.crf.CRFClassifier -prop harem-holdout.prop

    java -cp ../../stanford-ner.jar edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier harem-holdout.ser.gz -testFile harem.test >> result.txt

    cd ../../
done
